### ISSUE TITLE
Inputdriver ToDo List after merge into Master branch

### ISSUE THREAD

**Issue by MichaelPFrey** [openscad/openscad#2325]
after merging #2130 into master we can/should to:
- [ ] translation
   - [ ]  resolve ambiguous strings like "none"
   - [ ] update generate-potfiles.sh
   - [ ] update the translation files
   - [ ] fully translate for at least one language (ultimately proving that the translation really works)
Doing it while being in a feature branch could cause merge conflicts with the master branch.
