### ISSUE TITLE
Sync top level cmake setup with qmake build.

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#2518]
The qmake build is still the official one, but we do want to move to full cmake build eventually. So this issue is here as reminder to re-sync.

- [ ] Update build documentation
  - [ ] readme
  - [ ] wikibooks
- [ ] Update for the changes the inputdriver branch brought in
- [x] Enable HIDAPI support (see  #3720)
- [ ] Enable spnavd support
- [ ] add option to enable Sparkle on macOS (qmake `CONFIG=deploy`)
- [ ] fix `-DNULLGL=ON`
- [ ] fix/update `-DHEADLESS=OFF`
- [ ] find_library(QT5QSCINTILLA_LIBRARY) missing PATH_SUFFIXES unlike find_path(QT5QSCINTILLA_INCLUDE)
- [x] find_package(Qt5) missing Multimedia and target_link_libraries(OpenSCAD Qt5::Multimedia)
- [x] Add double-conversion
- [x] Add install target (application, color schemes, examples...)
- [ ] Verify behaviour of DEBUG flags as that can have big performance impact (some nubers in #2953)
- [x] Make sure to use plain `c++14` not `gnu` variants (see #3497)
- [x] Check `winconsole` build (see #3685)
- [x] Make sure `openscad.com` is console binary and `openscad.exe` is gui

**Comment by thehans** [comment]
I checked off a couple of the boxes here, 

Input driver stuff also works afaik, but I don't use any special input devices to test with.
I'm not sure what the `QT5QSCINTILLA_LIBRARY` issue is about, but has been working fine for me.
`HEADLESS` option was also working last time I checked.

I think maybe the only one still relevant is to add install targets.

**Comment by t-paul** [comment]
Closing, snapshot builds are `cmake` only for a while.
