### ISSUE TITLE
Update to Clipper2

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#4974]
Clipper2 is a rewrite of Clipper1 with a new API: https://angusj.com/clipper2/Docs/Overview.htm
Clipper2 is already used by the Manifold library.

We should upgrade OpenSCAD to use Clipper2.
TODO:
* [x] Add Clipper2; use a submodule rather than copying the code if feasible: #5501
* [x] Add support for using a system install of Clipper2 where available: #5501
* [x] Port to the Clipper2 API with no functional changes: #5501
* [x] Resolve test failures:
   * [x] `use-tests`: Possible M1/macOS Clipper bug, reported as https://github.com/AngusJohnson/Clipper2/issues/777
   * [x] `offset-tests`: Clipper2 changed the number of segments generated from rounded offset arc generation: Clipper1 rounded the wanted number of segments, while Clipper2 rounds _up_, causing generally more segments to be generated. Not much we can do about this as this is deep inside of Clipper, so best approach is probably to just updated the test goldens.
   * [x] `linear_extrude-scale-zero-tests`. Clipper1 is more aggressive at eliminating coincident vertices (vertices positioned on the line between its neighbors); the following yields 4 vertices in Clipper1, but 6 vertices in Clipper2: 
       ```
        translate([.5,0,0])square();
        translate([-.5,0,0])square();
        ```
        This is potentially a sign that Clipper2 isn't as good at cleaning polygons. Could be worth investigating in case it's a problem at scale. This turned out to be cause by Clipper2 no longer cleaning up collinear vertices. Setting `clipper.PreserveCollinear(false)` fixes it.
   * [x] `previewtest_minkowski2-crack` (CGAL mode): This fixed itself as we lowered the precision to 10^8
* [x] Look into using Clipper2's floating point support instead of converting to integers: Not supported for the offset operations we need. Also, the floating support is just a thin wrapper around integers, which we can easily implement ourselves for better flexibility.
* [x] Look for optimization and cleanup opportunities for using any Clipper API improvements: Not many opportunities. The Clipper2 C++ API is very similar to Clipper1, and does not offer much in terms of modern C++ features allowing us to clean up interface code.
* [x] Add test for fonts with overlapping contours. (#4980)
  * [x] Include svg test if applicable.
* [x] If feasible, disambiguate and clean up OpenSCAD's `polygon()` API (see #3154). -> not really feasible at this time.
* [x] Look into supporting the SVG fill-rule property (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule)
  * [x] Add import test (#4979)
  * [x] Add export test
  * [x] Support `fill-rule` property for import: -> #5503
* [x] Test Clipper2/Manifold combinations
   * [x] builtin Clipper2, builtin Manifold (default)
   * [x] System Clipper2, builtin Manifold 
   * [x] System Clipper2, System Manifold 
   * [x] builtin Clipper2, system Manifold 
* [x] Make OpenSCAD and Manifold use the same Clipper library.
   * [x] The missing piece is to allow a Manifold submodule to pick up OpenSCAD's Clipper2 submodule: https://github.com/elalish/manifold/pull/1115
   * [x] Update OpenSCAD macOS build to use latest Manifold master after merging https://github.com/elalish/manifold/pull/1115
   * [x] Update nightly macOS builds to use externally built Clipper2
