### ISSUE TITLE
Chore: remove python 2 specific code

### ISSUE THREAD

**Issue by Rotzbua** [openscad/openscad#5040]
There are some EOL python 2 specific (compatibility) code left in the scripts which can be remove.

### Example:

```python
from __future__ import print_function
```

### Tasks

- [x] remove compatibility imports
- [x] remove outdated imports
- [x] new classes declaration
- [x] update percent format
- [x] update format specifiers
- [x] simplify to `yield from`
- [x] redundant `open` modes
- [x] fix invalid escape sequences
