### ISSUE TITLE
Support externally built Manifold

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#5308]
We recently added the `-DUSE_BUILTIN_MANIFOLD` CMake flag, defaulting to true, but the support for setting this flag to false is incomplete.

TODO:
* [x] macOS: Build our own Manifold for distribution (macosx-build-dependencies.sh) and build OpenSCAD against it.
   * [x] Full Manifold w/deps build (fat binaries): #5310
   * [x] Allow building with internal manifold after previously installing it (i.e. override the system version). It looks like this is fixed by https://github.com/elalish/manifold/pull/1048 - needs testing after merge.
   * [x] Bonus: Build manifold deps separately -> defer Clipper2 until we upgrade OpenSCAD
   * [x] Bonus: Allow external deps (Clipper2, glm, tbb, onedpl) but builtin Manifold -> resolved by building manifod
   * [x] Q: Should USE_BUILTIN_MANIFOLD ideally override just manifold or also manifold's deps? -> Just manifold. We trust Manifold to do the right thing.
* [x] Linux: Make sure OpenSCAD can build against a distro-packaged Manifold.
   * [x] NixOS
   * [x] Gentoo
   * [x] Q: Are there any other distros packaging a recent manifold? -> unknown, but two is a good start
   * [x] Q: How is Clipper2 managed? -> as a separately packaged library
* [x] Windows: msys2 + MXE -> out of scope for now; we can use submodule.
* [x] Manage Manifold feature requests
   * [x] Use namespaced CMake libraries and targets (e.g. manifold::manifold instead of just manifold): https://github.com/elalish/manifold/issues/936
   * [x] If manifold built and installed its own clipper, a reinstall will not rebuild Clipper, but use the existing version. This is probably not intentional, unless Manifold has a way of querying for minimal required version and rebuild if and old version is installed _and_ it was built by manifold: https://github.com/elalish/manifold/issues/942 -> resolved by linking Clipper statically
   * [x] Unified library target name: https://github.com/elalish/manifold/pull/1048

**Comment by pca006132** [comment]
I think @cjmayo is packaging manifold for gentoo.

**Comment by kintel** [comment]
@cjmayo Thanks! I'll ping you when/if I make changes so we don't break anything.

**Comment by kintel** [comment]
@cjmayo How do you get around the manifold target name differences (`manifold` when using as submodule and `manifold::manifold` when using the installed version via `manifoldConfig.cmake`)?

**Comment by hzeller** [comment]
FWIW, building using the [system-provided manifold](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/op/openscad-unstable/package.nix#L31) with [`-DUSE_BUILTIN_MANIFOLD=OFF`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/op/openscad-unstable/package.nix#L110C6-L110C32) works fine out of the box in the Nixos packaging scripts.

**Comment by kintel** [comment]
@hzeller Something doesn't feel right; is `manifoldConfig.cmake` being picked up on NixOS?
I tried installing manifold, from a nix installation on Ubuntu, but only got `manifold-2.5.1-unstable-2024-09-15`. I don't know enough nix magic to figure out how to get the latest one :/

**Comment by pca006132** [comment]
We can just fix the target name differences in the upstream if needed.

**Comment by pca006132** [comment]
@elalish

**Comment by kintel** [comment]
@pca006132 Yeah, adding an ALIAS from manifold::manifold to the internal target might be a good thing.

At the moment I'm just curious how this works at all, as that might indicate a problem somewhere else.

**Comment by pca006132** [comment]
I got some time this weekend, will look into this issue.

**Comment by pca006132** [comment]
Looking at tbb, apparently they just do alias target. I guess we should do the same in the upstream.

**Comment by hzeller** [comment]
In https://github.com/openscad/openscad/issues/5308#issuecomment-2477987237 I was confused to not see manifold in the library info.
Looks like even if it is linked to OpenSCAD, it is never printed -- filed #5432

**Comment by hzeller** [comment]
@kintel the openscad-unstable version 2024-11-10 made it to the [nix unstable channel](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=openscad-unstable) if you want to try again.

**Comment by kintel** [comment]
@hzeller Looks like CMake changes are coming in manifold, so I'm waiting for that to settle before trying any distro stuff again.

**Comment by hzeller** [comment]
Ok, but I confirmed that apparently Manifold is compiled into the latest openscad-unstable, even without the cmake change. It is weird as the cmake does not emit a message when it finds manifold, but the final binary clearly uses manifold as rendered outputs retain color.

**Comment by pca006132** [comment]
The cmake changes should be settled now, at least before another issue is found...

**Comment by kintel** [comment]
Could someone double-check that Gentoo and NixOS can package the latest master (`8fb8c4865494bb536c0299fbfeb912109601df79` or newer) against Manifold V3?

**Comment by pca006132** [comment]
Yes, NixOS can build with 8fb8c4865494bb536c0299fbfeb912109601df79 using external manifold v3.

Some of the logs:
```
-- Offscreen OpenGL Context - using Unix EGL GLX
-- TBB: 2021.11.0
-- mainfold: 3.0.0
```

**Comment by kintel** [comment]
Thanks!
